In [1]:
import pandas as pd

In [4]:
sp= pd.read_csv('spotify_modified(cleaned gener).csv')

/tmp/ipython-input-2213391424.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  sp= pd.read_csv('spotify_modified(cleaned gener).csv')

EDA

In [22]:
sp.isna().sum()

artist              0
song                0
emotion             0
Genre               0
variance            0
Release Date        0
Key                 0
Tempo               0
Loudness            0
Explicit            0
Popularity          0
Energy              0
Danceability        0
Positiveness        0
Speechiness         0
Liveness            0
Acousticness        0
Instrumentalness    0
dtype: int64

In [23]:
sp.isnull().sum()

artist              0
song                0
emotion             0
Genre               0
variance            0
Release Date        0
Key                 0
Tempo               0
Loudness            0
Explicit            0
Popularity          0
Energy              0
Danceability        0
Positiveness        0
Speechiness         0
Liveness            0
Acousticness        0
Instrumentalness    0
dtype: int64

In [15]:
# Drop the 'Text After Delimiter' column
sp = sp.drop('Text After Delimiter', axis=1)
# Display the columns to confirm the column has been dropped
display(sp.columns)

KeyError: "['Text After Delimiter'] not found in axis"

In [21]:
# Display rows with any null values
display(sp[sp.isnull().any(axis=1)])

Empty DataFrame
Columns: [artist, song, emotion, Genre, variance, Release Date, Key, Tempo, Loudness, Explicit, Popularity, Energy, Danceability, Positiveness, Speechiness, Liveness, Acousticness, Instrumentalness]
Index: []

In [20]:
# Drop all rows with any null values in place
sp.dropna(inplace=True)

Shape of the DataFrame after dropping rows with nulls: (163070, 18)

,artist,song,emotion,Genre,variance,Release Date,Key,Tempo,Loudness,Explicit,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
0,ABBA,She's My Kind Of Girl,joy,pop,0.447619,2014,F Maj,128,-6.0,No,31.0,78.0,56.0,60.0,3.0,31.0,7.0,0.0
1,ABBA,"Andante, Andante",love,pop,0.202222,1980,A# Maj,102,-10.72,No,59.0,36.0,52.0,38.0,2.0,7.0,68.0,0.0
2,ABBA,As Good As New,sadness,pop,0.300881,1979,E Maj,139,-5.7,No,50.0,78.0,85.0,97.0,3.0,8.0,20.0,2.0
3,ABBA,Bang,joy,pop,0.355000,1975,F Maj,132,-3.0,No,52.0,76.0,50.0,89.0,3.0,32.0,3.0,0.0
4,ABBA,Bang-A-Boomerang,joy,pop,0.355000,1975,F Maj,132,-3.0,No,52.0,76.0,50.0,89.0,3.0,32.0,3.0,0.0

In [ ]:
display(sp['Genre'].value_counts())

Genre
unknown                 57479
pop                     45369
rap                     32949
alternative             18151
hip-hop                 17184
                        ...
dub                         1
psytrance                   1
bass house                  1
contemporary country        1
ska punk                    1
Name: count, Length: 158, dtype: int64

In [ ]:
# Get the unique values as a NumPy array
unique_genres_array = sp['Genre'].unique()

# Convert the NumPy array to a Python list
unique_genres_list = unique_genres_array.tolist()

# Print the list of unique genres
print(unique_genres_list)

['pop', 'comedy', 'rock', 'progressive', 'world', 'alternative', 'folk', 'opera', 'electronic', 'unknown', 'soundtrack', 'soul', 'jazz', 'metal', 'reggae', 'xmas', 'hip-hop', 'rap', 'christian', 'finnish', 'blues', 'country', 'wjlb-fm', "90's", 'guys who like to flaunt', 'math rock', 'vocaloid', 'ghetto sage', 'fm4', 'eye', 'spoken word', 'midtempo edm', 'very favoritest favorite', 'dance', 'gospel', 'beats', 'chill', 'myspotigrambot', 'rnb', 'rock band', 'anime', 'pain in my heart', 'bestest', 'eurovision song contest', <NA>, 'linedance catalan', 'fip', 'islam', 'colours', 'contemporary gospel', 'eurovision', 'disco', 'african', 'new york', 'brunicore', 'meme', 'hardcore', 'indie', 'sxsw', 'hh', 'bay area', 'colbert', 'canadian', 'birp', 'dubstep', 'australian', 'vocal', 'female vocalists', 'communism', 'crank wave', 'started from the bottom now we way up', 'kdot', 'british', 'punk', 'indie rock', 'boom bap', 'melodic hardcore', 'boygroup', 'driving', 'psychedelic', 'lo-fi', 'christmas', 'post-hardcore', 'r and b', 'wicked', 'linedance 2018', 'linedance', 'skramz', 'love at first listen', 'funk', 'rhythum and blues tag', 'sexy', 'uk hip hop', 'oldies', 'beautiful', 'norwegian', 'southern rock', 'actually this album is very good', 'awesome', 'praise & worship', 'sad', 'lovedbyme1', 'somafm', 'swing', 'sex scene songs', 'netherlands', '80s', 'blood brothers', 'inspirational', 'sxsw 2017', 'rockabilly', 'september', '60s', 'acoustic', 'aprils taste', 'alt-country', 'lang eng', 'days and nights', '6ix9ine', 'aitebar', 'bollywood', 'swedish', 'scrincic', 'detroit', 'blues rock', 'age of aquarius', 'thall', 'seen live', 'classical', 'atomic wedgie', 'singer-songwriter', 'wwe', 'hard rock', 'jpegmafia', 'redone', '70s', 'sean ono lennon', 'banjo', 'salon', 'indierock', 'rock ballad', 'greys anatomy', 'uncle reece', 'perfection', 'psychedelic rock', 'summer', 'go-go', 'slow jams tag', 'actresses', 'classic', 'jaydpeezy', 'father can you hear me', 'garage rock', 'new wave', 'tok1d', 'twang', '10s', 'death punk', 'modern country', 'stoner rock', 'coldwave', 'party', 'electro', 'martial neoclassical', 'volbeat', 'florida', 'this slaps', 'linedance 2019', 'trainspotters', 'love songs', 'quiet storm', 'tracey lee', 'badass', 'lts', 'names of people', 'teen wolf', 'slow jams', 'damon albarn', 'modern', 'fire', 'mike patton', 'cover', 'deathcore', 'from dusk till dawn', 'boring', 'sun and moon and stars and outer space music', '30 strand grass', 'post-vaporwave', '2step', 'synthwave', 'elizabeth marie lester', 'booty song', 'linedance 2016', 'gg', 'alt country', 'sadboi', 'surf rock', 'questions', 'emo', 'be-my-baby drum', 'experimental', 'hawaiian', 'piano', 'risque', 'brill building', 'sky - the sky is purple and things are right every day', 'he knows my name', 'title is a full sentence', 'post-rock', 'celtic rock', 'grunge', 'bo2015', 'on the radar', 'surf', 'mathcore', 'ska', 'video game music', 'glasgow rangers', 'handclaps', 'mellow', 'house', 'jam', 'answer song', 'doo wop', 'post-punk', 'soca', 'banned', 'gothic rock', '50s', 'melancholic', 'pay attention', 'irish', "grey's anatomy", 'hip hop', 'diplein', 'hidden hits', 'j-rock', 'garage punk', 'ost', 'bluegrass', 'test', 'radio paradise', 'needleontherecord', 'cute', 'the promise', 'eurovision 2020', 'brooklyn', 'punk rock', 'riverdale', 'classics', 'best of 2014', '7 of 10 stars', 'kid rock', 'poetry', 'land of a thousand dances', 'mod', 'southern gospel', 'psychobilly', 'nothing', 'sxsw 2015', 'himym', 'dustin lynch', '90s', 'prince', 'newfoundland', 'electro swing', 'ades', 'cool', 'if i die young remix', '5th year song', 'motown', 'torture', 'steampunk', 'scott pilgrim', 'chipmunks', 'female', 'chaotic hardcore', 'drag queens', 'gefaellt', 'rhythm and blues', '2010s', 'true blood', 'donk', 'navy', 'coolos', '2022 single', 'kiwi', 'smoking', 'drumstep', 'study', 'plugg', 'happy hardcore', 'tag', 'gay', 'gute laune', '2 stars', 'moves away from the mic to breathe in', 'nsfw show', 'shoegaze', 'chillout', 'urban', 'talley trio', 'indiena sound', 'dragonball z', 'lil uzi vert', 'determined', 'countries and continents', 'for jason', 'accordion', 'wrock', 'finding carter', 'non binary vocalist', 'fish', 'mlp', 'nickel sized hail', 'sunday service choir', 'soft rock', 'psychedelia', 'hilarious', 'styl-plus', 'bop', 'funk rock', 'art rock', 'texas country', 'uk hardcore', 'musical', 'edm', 'guitar virtuoso', 'baseball', 'da-stuff', 'favorite songs', 'american', '00s', 'eurovision 2021', 'downtempo', 'unreleased', 'lol', 'humor', 'bbc', 'trip-hop', 'pigeon', 'genial', 'personal favourites', 'der fuehrers face  spike jones', 'prince royce', 'trumpet', 'classic track', 'love', 'sophie tucker', 'eclectonia', 'theme song', 'bounced on my boy', 'memories', 'late night', 'mix', 'carmilla', 'misc', 'ethereal', 'worship and devotion', 'meditation', 'gertski pick', 'ddr', 'experimental rock', 'aussie', 'riot grrrl', 'songs on commercials', 'lucifer 3x17', 'linedance 2021', '2010s country rock', 'classical crossover', 'euro-trance', 'broken', 'gilles peterson', 'sweden', 'hardstyle', 'drum and bass', 'novelty', 'important', 'chorei', 'canadien', 'kid cudi', 'balkan', 'philippines', 'feelgood', 'wsc 3 final', 'bossa nova', 'linedance 2017', 'goth', 'celtic', 'fear', 'in-tru-mental', 'james bond', 'indietronica', 'saturday morning funhouse', 'gothic', 'gossip girl', 'imported by drip.feed', 'esc', 'grace and frankie', 'burgerrecords', 'lesotho', 'italo disco', 'sandwich', 'ypp', 'the vampire diaries', 'horror punk', 'young anna', 'sam salter', 'gilmore girls', 'cool picks', 'relaxing', 'vaporwave', 'latin freestyle', 'antm forever', 'future bass', 'ballad', 'male vocalists', 'featuring', 'real', 'songsof2014', 'what a lovely voice', 'discovered', 'little fires everywhere', 'sick', 'hercules the gospel truth', 'choir', 'roy', 'songs mentioning songs or artists', '2018 single', 'freestyle', 'kat fm', 'funny', 'spirit of the native americans', 'major', 'faves', 'english', 'n-a', 'worship', 'billboard number ones', 'macarthur park', 'lgbtq', 'my fair lady', 'whtd-fm', 'scream: the tv series', 'sus', 'evil diva', 'farewell', 'redneck', 'linedance 2020', 'hukilau', 'fatherhood', 'cumulative', 'a cappella', 'queen', 'beatbox', 'runaground', 'broad city', 'witch house', 'avant-garde', 'offset', '118 bpm', 'favoritas', 'noise', 'shitcore', 'ski movies', 'best of 2021', 'mixtape for next person i fall in love with', 'new zealand', 'trance', 'life is strange', 'noise rock', 'electronic ', 'classic country', 'my little pony', 'americana', 'phonk house', 'one more chance', 'song', 'darkwave', 'trip hop', 'sxsw 2014', 'glass', 'classic house', 'life and death', 'cover songs i want to hear', 'latin', 'berserk', 'feel good', 'c', 'nick and norah', 'sampled by kanye west', 'indian contemporary', 'paris texas', 'indian rock', 'queercore', '4 stars', 'beautiful sadness', 'beer', 'femboy', 'bitchbitchbitchbitch', '1m', '2010s funk blues', 'melodifestivalen', 'real screamo', 'favorite', 'hold on', 'hope', 'linedance 2023', 'numbers', 'will be listening to this until i am six feet under', 'oldie remix', 'hyphy', 'new discovery', 'ambient', 'bar25', 'blues tag', 'broadway', 'fav', 'backstage', 'nils lofgren', 'sslow', 'indonesia', 'glam rock', 'weirdcore', '6 of 10 stars', 'aaa', 'father', 'sea shanty', 'sia', 'japanese', 'dancehall', 'dauerbeschallung im umerziehungslager fuer nazis', 'techno', 'greek', 'mantra', '2015 single', 'korean', 'krautrock', 'amazing', 'french touch', 'dardbhare', 'speech', 'pedocore', 'chap-hop', 'mother', 'ted', 'eurodance', 'forced to listen to this in 6th grade', 'indie hip hop', 'dajon', 'new funk', 'norte shit', 'ryan ross', 'nice at night', 'indonesian', 'frauen und technik', 'chillstep', 'pair of kings', 'louisiana', 'wizard rock', 'egofm', 'russian', 'amv hell', 'afrobeats', 'lil jon', 'contemporary gospel tag', 'it is for me', 'kollektors eye', 'love at first listen   ', 'sex', 'movies', 'men of standard', 'cold', 'got my whiskey', 'melmaryns', 'the sopranos', 'eurobeat', 'familiarity', 'fortnite', 'ytmnd', 'melbourne sound', 'ayesha erotica', 'country rock', 'baked potato', 'food and drink', 'cabaret', 'cloud drill', 'real dank tunes', 'holiday', 'good', 'marie osmond', 'songs about work', 'unsigned', 'war and soldiers', 'energy', 'sofar cape town', 'malaika', 'nocna energia', 'proto-punk', 'indie rnb', 'jungle', 'songs that stop my heart', 'great', 'rodeo', 'disney', 'dreamsmp', 'andree', 'fhrockin', 'gtavc tracks', '13 reasons why', 'calypso', 'oi', 'wills roots radio', 'rock and roll', 'j dilla', 'i want to say thank you', 'calm', 'mullholland drive', 'desperate housewives season 2', 'val', 'terrace house', 'reb', 'funky', 'perfect', 'grime', 'old funk', 'patriotic', 'orange is the new black', 'linedance 2022', '2017 single', 'loneliness after dusk', 'latif', 'nigeria', 'parody', 'dark', 'entitlement', 'industrial', 'fruit and vegetables', 'women of country', 'gta3', 'grace hartzel', 'wave phonk', 'lucia maria', 'tik tok viral', 'lucifer 5x09', 'ofwgkta', 'funky house', 'sad songs', 'booty me down', 'emotional', 'papichulosrolas', 'opm', 'good left undone', 'members only', 'musicals', 'qqq', 'kim larsen', 'outkast', 'kiely williams', 'marseille', 'orgasmic', 'horror', 'the mortal instruments', 'female vocalist', 'scrubs', 'god is here clark sisters', 'great club track', 'a r rahman', 'phonk', 'classic dance', 'angel s last mission love ost', 'sunidhi chauhan', 'mariya', 'damian marley', 'lay you down', 'jay-z', 'uk funky', 'industrial rock', 'foodcore', 'goodbye', 'mexican', 'life unexpected', 'royalty crew', 'chanson', 'united kingdom', 'whimsical', 'jelai', 'loved', 'instrumental', 'new jack swing', 'fallout', 'choral', 'church', 'scottish', 'wedding', 'new', 'wolo999', 'arabic', 'conquerors', 'rupauls drag race', 'fashion', '2020 single', 'catchy', 'cha cha cha', 'roguesch0lar-loved', 'showtunes', 'rock n roll', 'maga', 'jeris johnson', 'romantic', 'flowers', 'fallon', 'officially shit', 'love love love', 'the past', 'asdfgh', 'c asian', 'hairy chest', 'bananacore', 'c best', 'tagalog songs', 'janieck', 'jane powell', 'the shit', 'music to get the pussy wet', 'a colors show', 'anthem', 'gajal', 'community', 'debut', 'baby making music', 'norway', 'skate punk', 'crazy', 'stonedbeat', 'male vocalist', '291ooo', 'opm rock', 'theatre', 'tamil', 'cowboy', 'corona', 'help', 'favorites', 'great vocals', 'screamo', 'vugube62', 'godspell', 'howard hewett', 'thinkgeek', 'all time favorite', 'hiphop', 'limfo', 'too british', 'suck my dick', 'hic hop', 'protest song', 'songs you have to hear before you die', 'lastfmsc', 'westcoast', 'high dive heart', 'eastsiders', 'sondheim', 'covers', 'commercial house', '20s', 'season of mist records', 'elliott smith', '#NAME?', 'madchester', 'mahogany sessions', 'title is imperative', 'dark cabaret', 'r&b', 'streamable track wants', 'mistagged track', 'dnb', 'hands up', 'sax', 'russian rock', 'easy listening', 'goodnight electric', 'gypsy punk', 'orchestral', 'ebm', 'glenn fredly', 'skins', 'remix', 'heavy stuff', 'chillwave', 'mars hill', 'weill', 'march george tandy', 'george m cohan', 'other', 'shooting stars', 'problem', 'bad moms', 'electro house', 'justified', 'hardcore punk', 'lucifer 5x06', 'hard', 'gackt', 'ugly', 'romanian', 'sun and moon and stars and outer space', 'grindcore', 'full gospel shabach', 'names', 'round', 'yodelling', '116 bpm', 'midwest emo', 'how i met your mother', 'girls name', 'politics', 'good song and band', 'played', 'neo-psych', 'fernando ortega', 'the bold type', '2016 loved', 'youtube', 'maybe', 'football', 'debut single', 'post malone', 'guitar', 'castiel', 'liquid funk', 'certified hood classic', 'bluesrock', 'psychopathic', '21st century in music', 'crash ride rock', 'need to look into', 'vocal harmonies', 'great quality stuff', 'answer songs', 'fictional eurovision 1', 'the republic of sarah', 'gregorian', 'title track', 'aa', 'really really oldies', 'last night of the proms', 'epic', 'exotica', 'steunfonds', 'i will never die', 'need for speed carbon', 'seattle', 'vibes', 'loveatfirstlisten', 'dance bhangra', 'bnai', 'gospel music', 'uk garage', 'miley cyrus', 'halloween', 'd-beat', 'future funk', 'down south', 'podo', 'writhing in emotional pain', 'beatdown hardcore', 'podz', 'happy', 'romantic dance', 'sound track', 'freedom', 'glitch hop', 'loveee', "r'n'b", 'sweet', 'mashup', 'creative commons', 'theme', 'j', 'nj', 'england', 'tribuna fm soft', 'praise and worship', 'pretty little liars', 'sxsw 2016', 'jesus is real', 'darwin hobbs', 'free european song contest 2021', 'dancinginthesky', 'headbanging', 'filk', 'everlasting', 'masterpiece', 'shame that they made so bad track', 'angry vibes', 'spiderverse', 'speed garage', 'miami bass', 'shit', 'shanties', 'quickstep', 'not grunge', 'amazing radio', "80's", 'sufu5a', 'the office', 'anarcho-punk', 'all actors and actresses', 'easy listening-d', 'kick ass', 'perluismimaster', 'casa da beja', 'slowcore', 'hotline miami', 'liked by dan shive', 'grandad', 'down4some1', 'girl group', 'animation meme', '1live fiehe', 'island', 'death rock', 'chris bender', 'sd', 'music for my siah', 'seasons', 'cookie dance', 'sports', 'chelsea', 'morocco', 'noisetrade', 'stupid funny', 'beach music', 'sleep and dreams', 'xd', '9 of 10 stars', 'joyful noise', 'fave', 'maximum volume', 'capella grey', 'gospel train', 'grandmix', 'club', 'songs about dicks', 'eurovision 2012', 'rip', 'deep house', 'mpb', 'west coast hiphop', 'buffy', 'coldplay', 'fleetwood mac', 'rac', 'helluva', 'french', 'hs', 'electro hop', 'carolina hurricanes', 'czhit', 'scat', 'tape', 'portland - bowling shoes', 'artisttoknow', 'crunk', 'future garage', 'bhangra', 'pit', 'kids', 'tryme', 'aam', 'i love you', 'heavy as fuck', 'haiti', 'stream', 'hay', 'discover weekly', 'rolling stone 500 greatest songs of all time', 'klutzniyacore', 'dirty south', 'della', 'awsome', 'nepalese', 'btb', 'spotify mistag', 'i love this song', 'come on england', 'shoegazefan', 'dub', 'queer', '2015 gif', 'intelligent snap music', 'cheer up', 'protest', 'east coast hip hop', 'baeza', 'kamaitachi', 'darkpsy', 'love song', 'mixtaperoom', 'pherfavs', 'fabric', 'b5', 'hair gel classics', 'sons of anarchy', 'psytrance', 'meyers', 'charity', 'fucking awesome', 'heard on pandora', 'gayatri mantra', 'halegirl', 'bass house', 'candy rain', 'sottish bagpipes', 'miami', 'favourite songs', 'denmark', 'contemporary country', 'melodifestivalen 2022', 'hott', 'amanda perez', 'zamrock', 'chingalinga', 'all', 'deadpool', 'ali g', 'check out this band', 'dua lipa', 'dance moms', 'playlista rmf fm', 'i can go to god in prayer', 'madden', 'naruto', 'i see you lord', 'arctic monkeys', 'ska punk', 'afrikan boy', 'sampled', 'marvel', 'light in piazza', 'male vocals', 'pakistani', 'literally me', 'archis', 'female singer', 'texas', 'szuruburu', 'eu', '8-bit', 'shandolyn', 'uk drill']

In [25]:
# Get the value counts of the 'Genre' column
genre_counts = sp['Genre'].value_counts()

# Filter for genres with a count of 3 or less
low_frequency_genres = genre_counts[genre_counts <= 3]

# Display the low frequency genres
display(low_frequency_genres)

Genre
vaporwave           3
drum and bass       3
downtempo           3
praise & worship    3
skramz              3
                   ..
jungle              1
funky house         1
phonk               1
industrial rock     1
choral              1
Name: count, Length: 71, dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

the differnce between strip() and split() is that split returns list

In [ ]:
ungenre =sp['clgenre'].unique()
ungenre

array(['pop', 'comedy', 'rock', ..., '808', 'shandolyn', 'uk drill'],
      dtype=object)

In [ ]:
sp['Genre'] = sp['Genre'].replace(r'^\d+$', pd.NA, regex=True)

In [ ]:
sp['Genre'] = sp['Genre'].apply(lambda x: None if isinstance(x, str) and x.strip().endswith("0s") else x)

In [ ]:
import pandas as pd

# القايمة بتاعة الجينرز المعتبرة
valid_genres = [
    "pop", "rock", "math rock", "indie rock", "punk rock", "hard rock", "southern rock",
    "psychedelic rock", "garage rock", "blues rock", "surf rock", "rockabilly", "stoner rock",
    "art rock", "funk rock", "noise rock", "progressive", "progressive rock", "alternative",
    "indie", "indietronica", "indie hip hop", "indie rnb", "folk", "alt-country", "country rock",
    "country", "modern country", "americana", "classic country", "texas country", "contemporary country",
    "hip hop", "hip-hop", "hh", "hic hop", "rap", "uk hip hop", "east coast hip hop", "west coast hiphop", "drill",
    "trap", "boom bap", "rnb", "r&b", "r and b", "rhythm and blues", "soul", "neo-soul", "motown",
    "blues", "bluesrock", "jazz", "swing", "bebop", "bossa nova",
    "metal", "deathcore", "chaotic hardcore", "melodic hardcore", "hardcore punk", "hardcore", "grindcore", "doom metal",
    "black metal", "heavy metal", "glam rock", "goth", "gothic", "gothic rock", "industrial", "industrial rock",
    "ska", "ska punk", "reggae", "dub", "dubstep", "drum and bass", "drumstep", "jungle", "dnb",
    "electronic", "electro", "edm", "house", "techno", "deep house", "electro house", "electro swing",
    "classic house", "funky house", "bass house", "chillstep", "chillwave", "chillout", "downtempo", "ambient",
    "experimental", "experimental rock", "industrial", "psytrance", "trance", "goa trance", "hardstyle",
    "future bass", "future funk", "vaporwave", "post-vaporwave", "synthwave", "new wave", "coldwave", "darkwave",
    "trip hop", "lo-fi", "shoegaze", "post-rock", "post-punk", "emo", "screamo", "real screamo", "skramz",
    "emo rap", "phonk", "phonk house", "wave phonk", "happy hardcore", "uk hardcore", "beatdown hardcore",
    "mathcore", "grunge", "riot grrrl", "proto-punk", "death punk", "psychobilly", "cowpunk",
    "acoustic", "singer-songwriter", "classical", "opera", "orchestral", "choral", "a cappella",
    "musical", "showtunes", "broadway", "cabaret", "dark cabaret",
    "latin", "latin freestyle", "reggaeton", "salsa", "bachata",
    "dance", "disco", "dancehall", "eurodance", "euro-trance", "eurobeat",
    "soundtrack", "ost", "anime", "video game music", "theme", "novelty",
    "holiday", "christmas", "xmas", "gospel", "southern gospel", "contemporary gospel", "praise & worship", "worship"
]

# فلترة العمود
sp["Genre"] = sp["Genre"].str.lower().str.strip()  # توحيد الكتابة
sp["Genre"] = sp["Genre"].apply(lambda x: x if x in valid_genres else "unknown")

In [28]:
sp.columns

Index(['artist', 'song', 'emotion', 'Genre', 'variance', 'Release Date', 'Key',
       'Tempo', 'Loudness', 'Explicit', 'Popularity', 'Energy', 'Danceability',
       'Positiveness', 'Speechiness', 'Liveness', 'Acousticness',
       'Instrumentalness'],
      dtype='object')

In [ ]:
sp.nunique()

artist                   30607
song                    159721
emotion                     10
Genre                      158
variance                 36641
Release Date                93
Key                         24
Tempo                      167
Loudness                  2953
Explicit                     2
Popularity                 100
Energy                     101
Danceability                94
Positiveness               100
Speechiness                 96
Liveness                   100
Acousticness               101
Instrumentalness           101
Text After Delimiter      1896
dtype: int64

In [26]:
sp.dtypes

artist               object
song                 object
emotion              object
Genre                object
variance            float64
Release Date          int64
Key                  object
Tempo                 int64
Loudness             object
Explicit             object
Popularity          float64
Energy              float64
Danceability        float64
Positiveness        float64
Speechiness         float64
Liveness            float64
Acousticness        float64
Instrumentalness    float64
dtype: object

In [24]:
sp.to_csv('final_spotify.csv', index=False)